export {default as Bollywood} from './bollywood/Bollywood'
export {default as Fitness} from './fitness/Fitness'
export {default as Food} from './food/Food'
export {default as Hollywood} from './hollywood/Hollywood'
export {default as Technology} from './technology/Technology'
export {default as Navbar} from './navbar/Navbar'
export {default as Home} from './home/Home'